
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJU1I1ajZxTU5nc1V3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMU1UWXlNVE13TlRWYUZ3MHpOakExTVRNeU1UTTFOVFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNzVEt3S3dDRWhjMUdyS0pNQnlpZGR6ZmhPV2wrbkNDcEVXTmRCaU1rOFZUTjh1bk4wVXhuL3BGVUUKYXRJU0R5NCs2dWRzU1lQWWNCT3FhOHpUc1Biamx5Zm5sZXE5RzRkUGJDcy9RaDVuN08yb01PWGJZaXE5WGxVaQpJeW43T1lQY2xRTTNtUnVDWUtyWEVDLzRRV2pDTlkyeEp4UTVidXh6WGFpbjNidXVBanNuRmZycTd0dThqWExUCnY0SmFqM2dHc0o4RnExNzdkaytiQ01scGc4RFZjNzM4ZjlSZjhjcklqeVdxU3Q4SkpRazkxWmkyV25sUFhNR24KL2V4OXJqRmZ5QmFUTCtJd2RaUDVpN2QwWlFYQkZjYWk4bEM4Y2R2Z2JYK0QwR1pSQ1VCYjBKeU1HaVRHRGRpTgppTUsyY1NhR25jTUswdC9zbkliOHN4aGI3R3Z4QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTYnFUNTU5em1XUm5QL0E1YkxpMUxzNm1NN216QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ050WE85WnJwLwpoZjNNbDNocUNhcW1XYy9JbnpTdDRITWp2QkdwMHlqb2xxSCtPWS90Nkx2Nm1JZ1ZuUEtkZjIzcTlKdVRDRTU2CjlYcjlHVXBvdWM1NkpaZ055UlVjWi9Va3R1eXpOaG9DelR5WnZGMi9SaHFWT2h3ZnNzRDdJTmNSajBQSjJib2oKYzNrSjdlRFlmZWt5MXdkZ0dWQmQ1YmdYUEN5ZTE2YU9ISHMwSXpYQTVNb2VLeUpLL0xmYitnL0tzaUQwK0JjWgpGeEUyMmgwM1FheDRBRVlRQ3FHeWxuS0NNWnVaRWc0NnlvZFpVcUlPNDdNOFR4eW9DVTkrNU1oZUJ4a2VyL1d3CnhVWHl6Q3lNeHIrZ1BsdG5NZnplenlIVXREcXFzTUd6ay9IR0dGZDY1SEpKQVRNUXVpUlc4MldyUU45bzBWVVgKTlhXNXV6LytTQWdiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://add83d69-8c61-42fa-b9cc-a60beafee541.eu-central-2-gw.linodelke.net:443
  name: lke604572

users:
- name: lke604572-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkNQd1JrdDg4bkFJR0NaSjE4QWM0Q1pTUkxrc2RENXVwUTQtLVJYY3RKVnMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tMm4ybXEiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMmEwODhhNGUtMjE3ZS00YWUzLThmNzYtOWEwM2YyZjVjNjliIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.T_I6-ufHRlOhNE8M8B50vtBs5nqceeepUVMna5aHSd-8-T1VACVgV2vtidagPP4UwqTeq0etQPDW_RvfrE8mzEa90a1-VvZMc9PurFHxyk4CdqF9eBBgEwLUolENkbc7QrZgInK0lkzy4rmFEb9xELggscAfxJ-hDuZsMfC4WfJydxWNiLuqFwrmJiZlRiCMECOF__kQvlJOBorOQbUj0cy0SCiEPTs0cc6K_6QMZfStTru9lwVBB7z4s-36q2TtEaotIu-V_VmUGYRGrtwgbF-YiLGK3yxI0yJlw4hvkeJcbE__b6aLjIeBdKCt-IDk6qr9tUpDmxfSpMPjpUktxw

contexts:
- context:
    cluster: lke604572
    namespace: default
    user: lke604572-admin
  name: lke604572-ctx

current-context: lke604572-ctx
