
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUkIxNDVlbzdZSnd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMU1UUXhPVEl3TVRaYUZ3MHpOakExTVRFeE9USTFNVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN1WXpQdE5ZMGJJU0hmR1h5Zm1pNkcvTWRkQnVjTmRPd3ZvNWJXcXlVZHIvRjR4RldJZUtNazRmV2kKV2lCcXFIYXNZRG5xS2lPYkR0NUNqOVMwTlFLSjFubXhiWGY1V0Q3U0J2VE8yQ2ltb2NJTTFHc29rSlJBL0N2VgpYajNKREphTTJsbm9ZOHRYK3J2cmhlUW9jQUZIbko1MVZXSXc2WEhuMUJxVVRnd29xWFFqdWdCS0d5Ui9pWDlCCnBnaWhQOUV0bncvMnFJdUN5NGU0Yml0SEhIYmpacFJOb0NYK2FiRDdGTUhqSkplVFV3MExxbVpPN1lBMHhiRlMKeHNNQjhtY0RLaGRvTURpTkFWVFBySjNQMkQwVkJzWjJpTUJMNDA1TGo1Tjh0ZGNlNGgvQjBybTVCSTZHdHZ3bwo2SDF2aVR1UVQvQ3pRYXhoY2VnaFhreGtsZVpiQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRQnNFZEFsVUQ0Qk9CcHowRndCQUxPd1NUaFd6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQi9YbjZIWmNFLwpSd1FTT1VMOHZkZFY3WlNLRVIzSVBzOEt2L3RIUG1TcndxVUJ1ZTMvOUVJbUYvaVdqVnpwblhQMHNWQXFWQUdTCkVicUJkQ3BoSnZ2SDMxenJpUnhWVUNsKzY5K3FnY2R2TXVFcVZSNFZSdU8rckFRVGFUb2ZndXNvYzU0R00zT2oKa29DMzBENHdPUllOTUhNUHlkT3AweXRLSWNUUGpTSDBveFBySVNkZkZ2cEczaUFMd0tUSGQrRjVyVG01VWtqVQpOUFNnOXNpb3E3T3IyZHdPOVZSMTdqUjlqdUFhUWpjaHdGUU05emJiUTlrWUhEcTJGL2xuSW9BcFVGNndybE9GCm9wRHRIczhZaFY3UmZ1UEVHaURDdlJsL2Vob3F0NDU5azFZc2x6Y3U5VS9HVzBISDUrRFpLQ09vbi9tOXlYQzMKR29sU2dFWkh1UFQzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://2b7b3adf-cb86-40dd-88dc-7641a4093193.eu-central-1-gw.linodelke.net:443
  name: lke603856

users:
- name: lke603856-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImlXVV93LUV2VzNQU0pOWHhOLVpFNjhjdi1rWWJ5bThOQXloLUlBb2hoZ28ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tenM3NzIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMTFhMDhlNjAtYzYyMi00ZTMzLWE0YWYtYjRmYzlhNzg0MWMwIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.j3po_6uS79M7iF-SSZ9HxFySfoQOUnsX3Edi7kVk6cIxe8-H8iFotWUM58gCdcDN71eRnY4UEqngpXYzV1F7H7WGAkfYPW30ArGo0mhfkIjiLZGFkqaImEXht1av7GMeTMXuXL9WS_P6utKIv4w6AYZdZGTu-SrgKuc1ua3bq6jHVUiHNuYObeE0lW4oGgIXdLMiSOzceWYFyR3zBrvgQOaVbHMLcd8WAJGg7iDTwN1TXodNaa6pUZL3DQxlohGtf-yU9Qvi2QtgDcwE2m2lquO1KKraFTRrIHWplWoi90dBOclRffEwM97nImaIhXByosYwHjuQ7rlpW5XKIvhABw

contexts:
- context:
    cluster: lke603856
    namespace: default
    user: lke603856-admin
  name: lke603856-ctx

current-context: lke603856-ctx
